### ISSUE TITLE
Success banner after successful round apply 

### ISSUE THREAD

**Issue by codenamejason** [gitcoinco/grants-hub#417]
**User Story**
As a project owner, 
I want to get a success confirmation after I've applied to a round
so that I know my application went through 

**Acceptance Criteria**
GIVEN that I submitted my application to a round
WHEN I am redirected to the Project Details page
THEN I see a success banner 

The final copy for success banner: 
"Thank you for applying to [Program Name] [Round Name]! 
Your application has been received, and the [Program Name] team will review and reach out with next steps."

**Tech Details**: 
* Related to: https://github.com/gitcoinco/grant-hub/pull/387

**Designs**
Figma: https://www.figma.com/file/obBzCCL8KwoTlVBb5g3ccN/Grant-Hub---Wireframes?node-id=2403%3A14112

<img width="694" alt="Screen Shot 2022-09-21 at 5 41 18 PM" src="https://user-images.githubusercontent.com/26017180/191615647-8b428ab8-8892-4390-a394-ff00480f13fc.png">

**Comment by michellema1208** [comment]
@codenamejason I just updated this ticket with the copy that we talked about in this conversation thread: https://github.com/gitcoinco/grant-hub/pull/387

The success banner should say: 
"Thank you for applying to [Program Name] [Round Name]!
Your application has been received, and the [Program Name] team will review and reach out with next steps."

I noticed in the conversation thread that because I used the "<>" symbol, so [Program Name] [Round Name] didn't show up in my comment, so resharing here just in case. 

One other thing: if we can add [Program Name] into the second sentence so it reads "... and the [Program Name] team will review and reach out with next steps", that would be great, so it's clear that by "team" we mean the _**Round Operator**_ team, not the Gitcoin team.
