### ISSUE TITLE
UI work > Create Navigation

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-hub#49]

**Comment by schultztimothy** [comment]
@michellema1208 @Etovardesign  I setup initial styling for the navigation, except did not style the wallet button. It looks like the wallet button within the navigation is meant to switch networks and also has a toggle.

![Image](https://user-images.githubusercontent.com/6887938/171514107-44460701-af39-4874-9a11-f5534c355e1d.png)

I feel like in order to complete this ticket to match the mockup we will need to decide which wallets we support? Also have mockups for what the dropdown will looks like as well as what actions it initiates.
