### ISSUE TITLE
Build mobile web view for Grant Hub

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-hub#58]
- can separate this into each page (landing page, dashboard, project details page, etc.)

**Comment by schultztimothy** [comment]
@michellema1208 @willsputra 

Just wanted to see if there was a mockup for mobile naviation since the navigation links are buttons on desktop. Thanks!

<img width="336" alt="Screen Shot 2022-06-13 at 11 58 07 AM" src="https://user-images.githubusercontent.com/6887938/173415594-78d757f2-91f3-439f-9128-7f70e1f7f6e5.png">
